locale: id_ID
url: 'https://muhdavi.com'
baseurl: ''
title: 'Muhammad Davi'

collections:
  posts:
    output: true
    permalink: /:collection/:title/
    excerpt_separator: <!--more-->
    paginate: 5
    lang: id_ID
    locale: id_ID
    url: 'https://muhdavi.com'
    baseurl: ''
    title: 'Muhammad Davi'

show_excerpts: true
paginate: 5
paginate_path: '/blog/:num/'

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock